server:
  port: 8700
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      enable-self-preservation: true
spring:
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin